services:
  app:
    build: .
    # 產出檔案有權限問題，指定user
    user: "${UID:-1000}:${GID:-1000}"
    command: mvn spring-boot:run
    stdin_open: true
    tty: true
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - MONGO_URI=mongodb://${MONGO_USERNAME:-agent}:${MONGO_PASSWORD:-agent}@mongo:27017/java_system_agent?authSource=admin
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/workspace:cached
      - ./logs:/workspace/logs
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-agent}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-agent}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
