package com.java.system.agent.answering.domain.observation;

/**
 * Runtime 以結構化方式表達的不確定性或拒絕原因
 */
public enum ObservationCode {
    AMBIGUOUS_REPOSITORY, AMBIGUOUS_ROUTE, AMBIGUOUS_SEMANTIC_TARGET, UNRESOLVED_CALL,
    OPAQUE_EXTERNAL_CALL, MISSING_SOURCE, PARTIAL_GRAPH, TRUNCATED_CANDIDATES,
    CONFLICTING_EVIDENCE, UNSUPPORTED_CLAIM, UNADDRESSED_PART, BLOCKING_UNCERTAINTY,
    ANSWER_REJECTION_REASON, ACTION_REJECTED, EXECUTION_FAILED, EXECUTION_NOT_IMPLEMENTED
}
