package com.java.system.agent.runtime.port.in;

public enum AnalysisTerminationReason {
    GOAL_COMPLETED,
    CAPABILITY_MISSING,
    PREREQUISITE_MISSING,
    SEMANTIC_AMBIGUOUS,
    SEMANTIC_FORBIDDEN,
    SEMANTIC_UNAVAILABLE,
    BUDGET_EXHAUSTED,
    NO_PROGRESS,
    REVISION_RESTART_LIMIT,
    CANCELLED,
    RUNTIME_FAILURE
}
