package com.java.semantic.callgraph.domain;

public enum CallType {
    INTERNAL_SERVICE,
    INTERNAL_CONTROLLER,
    INTERNAL_COMPONENT,
    INTERNAL_SCHEDULE,
    INTERNAL_INTERFACE_DEFAULT,
    DATA_ACCESS,
    RPC_CLIENT,
    MESSAGE_QUEUE,
    CACHE_OP,
    CYCLE_BACK_EDGE,
    TRAVERSAL_CUTOFF,
    INTERNAL_CLASS,
    UNRESOLVED,
    GENERATED_CODE,
    EXTERNAL_LIB,
    INTERFACE
}
