package com.java.semantic.callgraph.domain;

public enum ResolutionStrategy {
    JDT_CALL_HIERARCHY,
    JDT_DEFINITION_FALLBACK,
    SPRING_BEAN_BY_QUALIFIER,
    SPRING_BEAN_BY_PRIMARY,
    SPRING_SINGLE_IMPLEMENTATION,
    MYBATIS_MAPPER,
    SPRING_DATA_REPOSITORY,
    LOMBOK_GENERATED,
    EXTERNAL_LIBRARY,
    FEIGN_CLIENT,
    BUSINESS_READ_FORBIDDEN,
    SPRING_MULTIPLE_CANDIDATES,
    DATA_ACCESS_WITHOUT_EVIDENCE
}
